'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { useDetailPage } from '@/hooks/useDetailPage';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import { CheckCircle2, FileText, FileJson, ImageIcon, ArrowLeft } from 'lucide-react';

type ExportFormat = 'text' | 'json' | 'image';

export default function Step5Export() {
  const { state, dispatch } = useDetailPage();
  const { manuscriptSections, productInfo } = state;
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('text');
  const [exportDone, setExportDone] = useState(false);

  const visibleSections = [...manuscriptSections]
    .sort((a, b) => a.order - b.order)
    .filter((s) => s.visible);

  const buildTextContent = (): string => {
    const lines: string[] = [];
    lines.push(`===== ${productInfo.name || '상품'} 상세페이지 원고 =====`);
    lines.push('');
    visibleSections.forEach((section) => {
      lines.push(`[ ${section.title} ]`);
      lines.push('');
      lines.push(section.body);
      lines.push('');
      lines.push(`* 이미지 가이드: ${section.imageGuide}`);
      lines.push('');
      lines.push('---');
      lines.push('');
    });
    lines.push(`생성일: ${new Date().toLocaleDateString('ko-KR')}`);
    lines.push('Generated by DetailMaker');
    return lines.join('\n');
  };

  const buildJsonContent = (): string => {
    const data = {
      productName: productInfo.name,
      category: productInfo.category,
      price: productInfo.price,
      targetAudience: productInfo.targetAudience,
      generatedAt: new Date().toISOString(),
      sections: visibleSections.map((s) => ({
        id: s.id,
        sectionType: s.sectionType,
        title: s.title,
        body: s.body,
        imageGuide: s.imageGuide,
        order: s.order,
      })),
    };
    return JSON.stringify(data, null, 2);
  };

  const handleExport = () => {
    if (selectedFormat === 'image') {
      dispatch({ type: 'SET_STEP', payload: 4 });
      return;
    }

    const fileName = `${productInfo.name || '상세페이지'}_원고`;
    let content: string;
    let mimeType: string;
    let ext: string;

    if (selectedFormat === 'text') {
      content = buildTextContent();
      mimeType = 'text/plain;charset=utf-8';
      ext = 'txt';
    } else {
      content = buildJsonContent();
      mimeType = 'application/json;charset=utf-8';
      ext = 'json';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExportDone(true);
  };

  const formats: {
    key: ExportFormat;
    label: string;
    icon: React.ReactNode;
    desc: string;
    action?: string;
  }[] = [
    {
      key: 'text',
      label: '텍스트 파일',
      icon: <FileText className="w-7 h-7" />,
      desc: '섹션별 원고를 읽기 쉬운 텍스트 파일로 다운로드',
    },
    {
      key: 'json',
      label: 'JSON 파일',
      icon: <FileJson className="w-7 h-7" />,
      desc: '구조화된 데이터 형식으로 다운로드 (개발/연동용)',
    },
    {
      key: 'image',
      label: '이미지 (PNG)',
      icon: <ImageIcon className="w-7 h-7" />,
      desc: '섹션별 PNG 또는 전체 1장 이미지 — 이미지 에디터(Step 4)에서 다운로드',
      action: 'Step 4로 이동',
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="max-w-2xl mx-auto space-y-8"
    >
      <div className="text-center">
        <h2 className="text-2xl font-bold text-[#191F28] mb-2">내보내기</h2>
        <p className="text-[#8B95A1]">완성된 원고를 원하는 형식으로 다운로드하세요.</p>
      </div>

      <Card variant="elevated" padding="lg">
        <div className="text-center space-y-3">
          <div className="flex justify-center">
            <CheckCircle2 className="w-10 h-10 text-[#3182F6]" />
          </div>
          <h3 className="text-xl font-bold text-[#191F28]">원고가 완성되었습니다</h3>
          <div className="flex flex-wrap justify-center gap-4 text-sm text-[#8B95A1]">
            <span>상품: <strong className="text-[#191F28]">{productInfo.name || '—'}</strong></span>
            <span>섹션: <strong className="text-[#191F28]">{visibleSections.length}개</strong></span>
            {productInfo.price && (
              <span>가격: <strong className="text-[#191F28]">{productInfo.price}</strong></span>
            )}
          </div>
        </div>
      </Card>

      <div>
        <h3 className="text-xs font-medium text-[#8B95A1] mb-3 ml-1">
          내보내기 형식
        </h3>
        <div className="grid sm:grid-cols-3 gap-3">
          {formats.map((format) => (
            <Card
              key={format.key}
              variant="interactive"
              padding="md"
              selected={selectedFormat === format.key}
              onClick={() => {
                setSelectedFormat(format.key);
                setExportDone(false);
              }}
            >
              <div className="flex flex-col gap-3">
                <span className={`${selectedFormat === format.key ? 'text-[#3182F6]' : 'text-[#8B95A1]'}`}>
                  {format.icon}
                </span>
                <div>
                  <h4 className="font-semibold text-[#191F28] text-sm">{format.label}</h4>
                  <p className="text-xs text-[#8B95A1] mt-1 leading-relaxed">{format.desc}</p>
                  {format.action && selectedFormat === format.key && (
                    <p className="text-xs text-[#3182F6] mt-2 flex items-center gap-1">
                      <ArrowLeft className="w-3 h-3" />
                      {format.action}
                    </p>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      {exportDone && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="p-4 rounded-xl bg-[#3182F6]/10 border border-[#3182F6]/20 text-[#3182F6] text-sm text-center"
        >
          다운로드가 완료되었습니다.
        </motion.div>
      )}

      <div className="flex justify-between pt-4">
        <Button variant="ghost" onClick={() => dispatch({ type: 'PREV_STEP' })}>
          이전 (이미지 에디터)
        </Button>
        <div className="flex gap-3">
          <Button variant="outline" onClick={() => dispatch({ type: 'RESET' })}>
            새로 만들기
          </Button>
          <Button size="lg" onClick={handleExport}>
            {selectedFormat === 'image' ? 'Step 4로 이동' : '다운로드'}
          </Button>
        </div>
      </div>
    </motion.div>
  );
}
