import { CompositionElement, SectionComposition } from './composition-types';

// ---------------------------------------------------------------------------
// Placeholder replacement
// ---------------------------------------------------------------------------
function replacePlaceholders(
  value: string,
  colors: { primary: string; accent: string; text: string }
): string {
  return value
    .replace(/\{primary\}/g, colors.primary)
    .replace(/\{accent\}/g, colors.accent)
    .replace(/\{text\}/g, colors.text);
}

function processElements(
  elements: CompositionElement[],
  colors: { primary: string; accent: string; text: string }
): CompositionElement[] {
  return elements.map((el) => {
    const processed: CompositionElement = { ...el };

    const strFields: (keyof CompositionElement)[] = [
      'fill', 'stroke', 'color', 'text', 'src',
    ];
    for (const field of strFields) {
      const v = processed[field as keyof CompositionElement];
      if (typeof v === 'string') {
        (processed as unknown as Record<string, unknown>)[field] = replacePlaceholders(v, colors);
      }
    }

    if (processed.gradient) {
      processed.gradient = {
        ...processed.gradient,
        from: replacePlaceholders(processed.gradient.from, colors),
        to: replacePlaceholders(processed.gradient.to, colors),
      };
    }

    return processed;
  });
}

// ---------------------------------------------------------------------------
// Template definitions
// ---------------------------------------------------------------------------

// 1. HERO — 860 × 900
const heroTemplate = (): CompositionElement[] => [
  // Background gradient rect
  {
    id: 'hero-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 900,
    gradient: { from: '{primary}', to: '#1a1a2e', direction: '160deg' },
    opacity: 1,
    locked: true,
    name: 'Background',
  },
  // Decorative large circle — top right
  {
    id: 'hero-deco-circle-tr',
    type: 'circle',
    x: 660, y: -80, width: 340, height: 340,
    fill: '{accent}',
    opacity: 0.12,
    locked: true,
    name: 'Deco Circle TR',
  },
  // Decorative large circle — bottom left
  {
    id: 'hero-deco-circle-bl',
    type: 'circle',
    x: -100, y: 620, width: 300, height: 300,
    fill: '{accent}',
    opacity: 0.10,
    locked: true,
    name: 'Deco Circle BL',
  },
  // Decorative small circle — mid-left
  {
    id: 'hero-deco-circle-ml',
    type: 'circle',
    x: 40, y: 260, width: 90, height: 90,
    fill: '{accent}',
    opacity: 0.18,
    locked: true,
    name: 'Deco Circle ML',
  },
  // Decorative small circle — mid-right
  {
    id: 'hero-deco-circle-mr',
    type: 'circle',
    x: 740, y: 400, width: 70, height: 70,
    fill: '#ffffff',
    opacity: 0.08,
    locked: true,
    name: 'Deco Circle MR',
  },
  // Accent horizontal line — top
  {
    id: 'hero-accent-line-top',
    type: 'line',
    x: 180, y: 80, width: 500, height: 3,
    fill: '{accent}',
    opacity: 0.5,
    locked: true,
    name: 'Accent Line Top',
  },
  // Product image area (center)
  {
    id: 'hero-img',
    type: 'image',
    x: 280, y: 140, width: 300, height: 380,
    fill: 'rgba(255,255,255,0.06)',
    objectFit: 'contain',
    cornerRadius: 20,
    shadow: true,
    draggable: true,
    name: 'Product Image',
  },
  // Image inner glow ring
  {
    id: 'hero-img-ring',
    type: 'rect',
    x: 270, y: 130, width: 320, height: 400,
    fill: 'transparent',
    stroke: '{accent}',
    strokeWidth: 2,
    cornerRadius: 24,
    opacity: 0.35,
    locked: true,
    name: 'Image Ring',
  },
  // Hero badge — top left of image
  {
    id: 'hero-badge',
    type: 'badge',
    x: 240, y: 148, width: 110, height: 32,
    fill: '{accent}',
    cornerRadius: 16,
    opacity: 0.95,
    draggable: true,
    name: 'Badge',
  },
  {
    id: 'hero-badge-text',
    type: 'text',
    x: 240, y: 156, width: 110, height: 20,
    text: '✦ NEW',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Badge Text',
  },
  // Main title
  {
    id: 'hero-title',
    type: 'text',
    x: 60, y: 550, width: 740, height: 90,
    text: '제품 핵심 타이틀',
    fontSize: 52,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.15,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Hero Title',
  },
  // Accent underline below title
  {
    id: 'hero-title-underline',
    type: 'rect',
    x: 310, y: 648, width: 240, height: 5,
    fill: '{accent}',
    cornerRadius: 3,
    opacity: 0.9,
    locked: true,
    name: 'Title Underline',
  },
  // Subtitle
  {
    id: 'hero-subtitle',
    type: 'text',
    x: 100, y: 668, width: 660, height: 60,
    text: '핵심 가치와 차별점을 두 줄로 설명하는 서브타이틀 문장입니다.',
    fontSize: 18,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.75)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },
  // Accent divider dots row
  {
    id: 'hero-dot-1',
    type: 'circle',
    x: 402, y: 750, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.9,
    locked: true,
    name: 'Dot 1',
  },
  {
    id: 'hero-dot-2',
    type: 'circle',
    x: 418, y: 750, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.5,
    locked: true,
    name: 'Dot 2',
  },
  {
    id: 'hero-dot-3',
    type: 'circle',
    x: 434, y: 750, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.25,
    locked: true,
    name: 'Dot 3',
  },
  // Gradient bottom bar
  {
    id: 'hero-bottom-bar',
    type: 'rect',
    x: 0, y: 780, width: 860, height: 120,
    gradient: { from: 'rgba(0,0,0,0)', to: 'rgba(0,0,0,0.55)', direction: '180deg' },
    opacity: 1,
    locked: true,
    name: 'Bottom Bar',
  },
  // Bottom bar text — stat 1
  {
    id: 'hero-stat-1',
    type: 'text',
    x: 100, y: 830, width: 160, height: 50,
    text: '98%\n만족도',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.3,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Stat 1',
  },
  // Divider
  {
    id: 'hero-stat-div-1',
    type: 'line',
    x: 280, y: 830, width: 2, height: 50,
    fill: 'rgba(255,255,255,0.25)',
    locked: true,
    name: 'Stat Divider 1',
  },
  {
    id: 'hero-stat-2',
    type: 'text',
    x: 320, y: 830, width: 160, height: 50,
    text: '5만+\n누적 판매',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.3,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Stat 2',
  },
  {
    id: 'hero-stat-div-2',
    type: 'line',
    x: 500, y: 830, width: 2, height: 50,
    fill: 'rgba(255,255,255,0.25)',
    locked: true,
    name: 'Stat Divider 2',
  },
  {
    id: 'hero-stat-3',
    type: 'text',
    x: 540, y: 830, width: 160, height: 50,
    text: '4.9★\n평균 평점',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.3,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Stat 3',
  },
];

// 2. PROBLEM — 860 × 1000
const problemTemplate = (): CompositionElement[] => [
  // Background
  {
    id: 'problem-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 1000,
    fill: '#f5f5f7',
    locked: true,
    name: 'Background',
  },
  // Top accent bar
  {
    id: 'problem-top-bar',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 6,
    fill: '{accent}',
    locked: true,
    name: 'Top Bar',
  },
  // Section label
  {
    id: 'problem-label',
    type: 'text',
    x: 0, y: 60, width: 860, height: 28,
    text: '이런 불편함, 겪고 계시지 않나요?',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Section Label',
  },
  // Main title
  {
    id: 'problem-title',
    type: 'text',
    x: 60, y: 100, width: 740, height: 80,
    text: '기존 방식의 한계를 넘어서다',
    fontSize: 42,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Problem Title',
  },
  // Title underline
  {
    id: 'problem-title-line',
    type: 'rect',
    x: 340, y: 190, width: 180, height: 4,
    fill: '{accent}',
    cornerRadius: 2,
    locked: true,
    name: 'Title Line',
  },
  // Subtitle
  {
    id: 'problem-subtitle',
    type: 'text',
    x: 120, y: 208, width: 620, height: 44,
    text: '많은 분들이 반복적으로 겪는 세 가지 핵심 문제점을 정확히 파악했습니다.',
    fontSize: 15,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.6,
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },

  // --- Card 1 ---
  {
    id: 'problem-card-1',
    type: 'rect',
    x: 40, y: 280, width: 240, height: 360,
    fill: '#ffffff',
    cornerRadius: 16,
    shadow: true,
    locked: true,
    name: 'Card 1',
  },
  {
    id: 'problem-card-1-top',
    type: 'rect',
    x: 40, y: 280, width: 240, height: 6,
    fill: '{accent}',
    cornerRadius: 16,
    locked: true,
    name: 'Card 1 Top Border',
  },
  {
    id: 'problem-card-1-icon-bg',
    type: 'circle',
    x: 115, y: 316, width: 90, height: 90,
    fill: '{primary}',
    opacity: 0.1,
    locked: true,
    name: 'Card 1 Icon BG',
  },
  {
    id: 'problem-card-1-icon',
    type: 'text',
    x: 115, y: 340, width: 90, height: 50,
    text: '⚠️',
    fontSize: 32,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 1 Icon',
  },
  {
    id: 'problem-card-1-title',
    type: 'text',
    x: 56, y: 430, width: 208, height: 40,
    text: '시간 낭비',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 1 Title',
  },
  {
    id: 'problem-card-1-desc',
    type: 'text',
    x: 60, y: 480, width: 200, height: 120,
    text: '반복적인 작업에 소중한 시간을 낭비하고 있어 정작 중요한 일에 집중하지 못하고 있습니다.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 1 Desc',
  },

  // --- Card 2 ---
  {
    id: 'problem-card-2',
    type: 'rect',
    x: 310, y: 280, width: 240, height: 360,
    fill: '#ffffff',
    cornerRadius: 16,
    shadow: true,
    locked: true,
    name: 'Card 2',
  },
  {
    id: 'problem-card-2-top',
    type: 'rect',
    x: 310, y: 280, width: 240, height: 6,
    fill: '{primary}',
    cornerRadius: 16,
    locked: true,
    name: 'Card 2 Top Border',
  },
  {
    id: 'problem-card-2-icon-bg',
    type: 'circle',
    x: 385, y: 316, width: 90, height: 90,
    fill: '{primary}',
    opacity: 0.1,
    locked: true,
    name: 'Card 2 Icon BG',
  },
  {
    id: 'problem-card-2-icon',
    type: 'text',
    x: 385, y: 340, width: 90, height: 50,
    text: '💸',
    fontSize: 32,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 2 Icon',
  },
  {
    id: 'problem-card-2-title',
    type: 'text',
    x: 326, y: 430, width: 208, height: 40,
    text: '비용 증가',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 2 Title',
  },
  {
    id: 'problem-card-2-desc',
    type: 'text',
    x: 330, y: 480, width: 200, height: 120,
    text: '비효율적인 프로세스로 인해 예상보다 훨씬 많은 비용이 지속적으로 발생하고 있습니다.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 2 Desc',
  },

  // --- Card 3 ---
  {
    id: 'problem-card-3',
    type: 'rect',
    x: 580, y: 280, width: 240, height: 360,
    fill: '#ffffff',
    cornerRadius: 16,
    shadow: true,
    locked: true,
    name: 'Card 3',
  },
  {
    id: 'problem-card-3-top',
    type: 'rect',
    x: 580, y: 280, width: 240, height: 6,
    fill: '{accent}',
    cornerRadius: 16,
    locked: true,
    name: 'Card 3 Top Border',
  },
  {
    id: 'problem-card-3-icon-bg',
    type: 'circle',
    x: 655, y: 316, width: 90, height: 90,
    fill: '{primary}',
    opacity: 0.1,
    locked: true,
    name: 'Card 3 Icon BG',
  },
  {
    id: 'problem-card-3-icon',
    type: 'text',
    x: 655, y: 340, width: 90, height: 50,
    text: '😤',
    fontSize: 32,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 3 Icon',
  },
  {
    id: 'problem-card-3-title',
    type: 'text',
    x: 596, y: 430, width: 208, height: 40,
    text: '스트레스',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 3 Title',
  },
  {
    id: 'problem-card-3-desc',
    type: 'text',
    x: 600, y: 480, width: 200, height: 120,
    text: '복잡한 과정과 불확실한 결과로 인해 매일 스트레스를 받으며 번아웃 위기에 처해 있습니다.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 3 Desc',
  },

  // Bottom summary bar
  {
    id: 'problem-bottom-bar',
    type: 'rect',
    x: 40, y: 700, width: 780, height: 80,
    fill: '{primary}',
    cornerRadius: 12,
    opacity: 0.08,
    locked: true,
    name: 'Bottom Summary Bar',
  },
  {
    id: 'problem-bottom-text',
    type: 'text',
    x: 60, y: 726, width: 740, height: 34,
    text: '이 세 가지 문제, 저도 똑같이 겪었습니다. 그래서 만들었습니다.',
    fontSize: 16,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{primary}',
    draggable: true,
    editable: true,
    name: 'Bottom Summary Text',
  },

  // Decorative bottom dots
  {
    id: 'problem-deco-dot-1',
    type: 'circle',
    x: 60, y: 840, width: 12, height: 12,
    fill: '{accent}',
    opacity: 0.3,
    locked: true,
    name: 'Deco Dot 1',
  },
  {
    id: 'problem-deco-dot-2',
    type: 'circle',
    x: 82, y: 840, width: 12, height: 12,
    fill: '{accent}',
    opacity: 0.15,
    locked: true,
    name: 'Deco Dot 2',
  },
  {
    id: 'problem-deco-rect',
    type: 'rect',
    x: 0, y: 920, width: 860, height: 80,
    fill: '#ebebeb',
    locked: true,
    name: 'Deco Bottom Rect',
  },
  {
    id: 'problem-deco-bottom-text',
    type: 'text',
    x: 0, y: 944, width: 860, height: 34,
    text: '지금 바로 해결책을 확인하세요 ↓',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(0,0,0,0.4)',
    draggable: true,
    editable: true,
    name: 'CTA Hint',
  },
];

// 3. SOLUTION — 860 × 900
const solutionTemplate = (): CompositionElement[] => [
  // Background
  {
    id: 'solution-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 900,
    fill: '#ffffff',
    locked: true,
    name: 'Background',
  },
  // Top accent bar
  {
    id: 'solution-accent-bar',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 8,
    gradient: { from: '{primary}', to: '{accent}', direction: '90deg' },
    locked: true,
    name: 'Accent Bar',
  },
  // Section label pill
  {
    id: 'solution-label-bg',
    type: 'rect',
    x: 330, y: 50, width: 200, height: 34,
    fill: '{accent}',
    cornerRadius: 17,
    opacity: 0.12,
    locked: true,
    name: 'Label BG',
  },
  {
    id: 'solution-label',
    type: 'text',
    x: 330, y: 58, width: 200, height: 22,
    text: '✦ 솔루션',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Label',
  },
  // Main title
  {
    id: 'solution-title',
    type: 'text',
    x: 60, y: 100, width: 740, height: 90,
    text: '단 하나의 솔루션으로\n모든 문제가 해결됩니다',
    fontSize: 40,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.25,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Product image area
  {
    id: 'solution-img-shadow',
    type: 'rect',
    x: 180, y: 215, width: 500, height: 340,
    fill: '{primary}',
    cornerRadius: 24,
    opacity: 0.08,
    locked: true,
    name: 'Image Shadow',
  },
  {
    id: 'solution-img',
    type: 'image',
    x: 190, y: 200, width: 480, height: 330,
    fill: 'rgba(0,0,0,0.04)',
    cornerRadius: 20,
    objectFit: 'contain',
    shadow: true,
    draggable: true,
    name: 'Product Image',
  },
  // Image corner accent
  {
    id: 'solution-img-corner-tl',
    type: 'rect',
    x: 190, y: 200, width: 40, height: 5,
    fill: '{accent}',
    cornerRadius: 3,
    locked: true,
    name: 'Corner TL H',
  },
  {
    id: 'solution-img-corner-tl-v',
    type: 'rect',
    x: 190, y: 200, width: 5, height: 40,
    fill: '{accent}',
    cornerRadius: 3,
    locked: true,
    name: 'Corner TL V',
  },
  {
    id: 'solution-img-corner-br',
    type: 'rect',
    x: 625, y: 525, width: 45, height: 5,
    fill: '{accent}',
    cornerRadius: 3,
    locked: true,
    name: 'Corner BR H',
  },
  {
    id: 'solution-img-corner-br-v',
    type: 'rect',
    x: 665, y: 490, width: 5, height: 40,
    fill: '{accent}',
    cornerRadius: 3,
    locked: true,
    name: 'Corner BR V',
  },

  // Check pill items row
  {
    id: 'solution-check-1-bg',
    type: 'rect',
    x: 40, y: 560, width: 240, height: 46,
    fill: '#f0fdf4',
    cornerRadius: 23,
    locked: true,
    name: 'Check 1 BG',
  },
  {
    id: 'solution-check-1',
    type: 'text',
    x: 52, y: 573, width: 216, height: 22,
    text: '✓  즉시 사용 가능',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#16a34a',
    draggable: true,
    editable: true,
    name: 'Check 1',
  },
  {
    id: 'solution-check-2-bg',
    type: 'rect',
    x: 310, y: 560, width: 240, height: 46,
    fill: '#f0fdf4',
    cornerRadius: 23,
    locked: true,
    name: 'Check 2 BG',
  },
  {
    id: 'solution-check-2',
    type: 'text',
    x: 322, y: 573, width: 216, height: 22,
    text: '✓  전문가 검증 완료',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#16a34a',
    draggable: true,
    editable: true,
    name: 'Check 2',
  },
  {
    id: 'solution-check-3-bg',
    type: 'rect',
    x: 580, y: 560, width: 240, height: 46,
    fill: '#f0fdf4',
    cornerRadius: 23,
    locked: true,
    name: 'Check 3 BG',
  },
  {
    id: 'solution-check-3',
    type: 'text',
    x: 592, y: 573, width: 216, height: 22,
    text: '✓  30일 무료 체험',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#16a34a',
    draggable: true,
    editable: true,
    name: 'Check 3',
  },

  // Description text
  {
    id: 'solution-desc',
    type: 'text',
    x: 100, y: 638, width: 660, height: 80,
    text: '복잡한 설정 없이 바로 시작할 수 있습니다. 검증된 방법론을 기반으로 당신의 문제를 근본적으로 해결해 드립니다. 지금 경험해 보세요.',
    fontSize: 15,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.7,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Description',
  },

  // Bottom divider line
  {
    id: 'solution-divider',
    type: 'line',
    x: 80, y: 750, width: 700, height: 2,
    fill: 'rgba(0,0,0,0.06)',
    locked: true,
    name: 'Bottom Divider',
  },
  // Bottom deco circles
  {
    id: 'solution-deco-circle-left',
    type: 'circle',
    x: -60, y: 700, width: 200, height: 200,
    fill: '{accent}',
    opacity: 0.05,
    locked: true,
    name: 'Deco Circle Left',
  },
  {
    id: 'solution-deco-circle-right',
    type: 'circle',
    x: 720, y: 660, width: 200, height: 200,
    fill: '{primary}',
    opacity: 0.05,
    locked: true,
    name: 'Deco Circle Right',
  },
  // Bottom note
  {
    id: 'solution-bottom-note',
    type: 'text',
    x: 0, y: 820, width: 860, height: 30,
    text: '* 개인 차에 따라 결과가 다를 수 있습니다.',
    fontSize: 11,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(0,0,0,0.3)',
    draggable: true,
    editable: true,
    name: 'Bottom Note',
  },
];

// 4. FEATURES — 860 × 1100
const featuresTemplate = (): CompositionElement[] => [
  // Dark primary background
  {
    id: 'features-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 1100,
    fill: '{primary}',
    locked: true,
    name: 'Background',
  },
  // Subtle noise texture overlay
  {
    id: 'features-bg-overlay',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 1100,
    fill: 'rgba(0,0,0,0.25)',
    locked: true,
    name: 'Overlay',
  },
  // Decorative corner circles
  {
    id: 'features-deco-tr',
    type: 'circle',
    x: 720, y: -80, width: 280, height: 280,
    fill: '{accent}',
    opacity: 0.08,
    locked: true,
    name: 'Deco TR',
  },
  {
    id: 'features-deco-bl',
    type: 'circle',
    x: -60, y: 880, width: 240, height: 240,
    fill: '{accent}',
    opacity: 0.07,
    locked: true,
    name: 'Deco BL',
  },
  // Section label
  {
    id: 'features-label',
    type: 'text',
    x: 0, y: 60, width: 860, height: 26,
    text: '— FEATURES —',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Label',
  },
  // Title
  {
    id: 'features-title',
    type: 'text',
    x: 60, y: 98, width: 740, height: 80,
    text: '압도적인 4가지 핵심 기능',
    fontSize: 44,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Title accent underline
  {
    id: 'features-title-ul',
    type: 'rect',
    x: 290, y: 188, width: 280, height: 4,
    fill: '{accent}',
    cornerRadius: 2,
    locked: true,
    name: 'Title Underline',
  },
  // Subtitle
  {
    id: 'features-subtitle',
    type: 'text',
    x: 140, y: 206, width: 580, height: 40,
    text: '경쟁사와 비교할 수 없는 독자적인 기술력으로 만든 기능들입니다.',
    fontSize: 14,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.55)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },

  // --- Card grid: 2x2, each 380x300 ---
  // Card 1 (top-left)
  {
    id: 'features-card-1',
    type: 'rect',
    x: 40, y: 280, width: 380, height: 300,
    fill: '#ffffff',
    cornerRadius: 18,
    shadow: true,
    opacity: 0.97,
    locked: true,
    name: 'Card 1',
  },
  {
    id: 'features-card-1-icon-bg',
    type: 'circle',
    x: 56, y: 306, width: 64, height: 64,
    fill: '{accent}',
    opacity: 0.15,
    locked: true,
    name: 'Card 1 Icon BG',
  },
  {
    id: 'features-card-1-icon',
    type: 'text',
    x: 56, y: 318, width: 64, height: 40,
    text: '⚡',
    fontSize: 28,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 1 Icon',
  },
  {
    id: 'features-card-1-title',
    type: 'text',
    x: 140, y: 306, width: 264, height: 36,
    text: '초고속 처리',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 1 Title',
  },
  {
    id: 'features-card-1-desc',
    type: 'text',
    x: 56, y: 380, width: 300, height: 100,
    text: '업계 최초 병렬 처리 엔진으로 기존 대비 10배 빠른 속도를 경험하세요. 대용량 데이터도 단 몇 초 안에 처리됩니다.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 1 Desc',
  },
  {
    id: 'features-card-1-tag',
    type: 'rect',
    x: 56, y: 530, width: 80, height: 24,
    fill: '{accent}',
    cornerRadius: 12,
    opacity: 0.15,
    locked: true,
    name: 'Card 1 Tag BG',
  },
  {
    id: 'features-card-1-tag-text',
    type: 'text',
    x: 56, y: 535, width: 80, height: 16,
    text: '특허 기술',
    fontSize: 10,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Card 1 Tag',
  },

  // Card 2 (top-right)
  {
    id: 'features-card-2',
    type: 'rect',
    x: 440, y: 280, width: 380, height: 300,
    fill: '#ffffff',
    cornerRadius: 18,
    shadow: true,
    opacity: 0.97,
    locked: true,
    name: 'Card 2',
  },
  {
    id: 'features-card-2-icon-bg',
    type: 'circle',
    x: 456, y: 306, width: 64, height: 64,
    fill: '{primary}',
    opacity: 0.12,
    locked: true,
    name: 'Card 2 Icon BG',
  },
  {
    id: 'features-card-2-icon',
    type: 'text',
    x: 456, y: 318, width: 64, height: 40,
    text: '🔒',
    fontSize: 28,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 2 Icon',
  },
  {
    id: 'features-card-2-title',
    type: 'text',
    x: 540, y: 306, width: 264, height: 36,
    text: '완벽한 보안',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 2 Title',
  },
  {
    id: 'features-card-2-desc',
    type: 'text',
    x: 456, y: 380, width: 300, height: 100,
    text: '군사급 AES-256 암호화로 개인정보를 철저히 보호합니다. ISO 27001 인증 획득, 제3자 보안 감사 통과.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 2 Desc',
  },
  {
    id: 'features-card-2-tag',
    type: 'rect',
    x: 456, y: 530, width: 90, height: 24,
    fill: '{primary}',
    cornerRadius: 12,
    opacity: 0.12,
    locked: true,
    name: 'Card 2 Tag BG',
  },
  {
    id: 'features-card-2-tag-text',
    type: 'text',
    x: 456, y: 535, width: 90, height: 16,
    text: 'ISO 인증',
    fontSize: 10,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{primary}',
    draggable: true,
    editable: true,
    name: 'Card 2 Tag',
  },

  // Card 3 (bottom-left)
  {
    id: 'features-card-3',
    type: 'rect',
    x: 40, y: 600, width: 380, height: 300,
    fill: '#ffffff',
    cornerRadius: 18,
    shadow: true,
    opacity: 0.97,
    locked: true,
    name: 'Card 3',
  },
  {
    id: 'features-card-3-icon-bg',
    type: 'circle',
    x: 56, y: 626, width: 64, height: 64,
    fill: '{accent}',
    opacity: 0.15,
    locked: true,
    name: 'Card 3 Icon BG',
  },
  {
    id: 'features-card-3-icon',
    type: 'text',
    x: 56, y: 638, width: 64, height: 40,
    text: '🤖',
    fontSize: 28,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 3 Icon',
  },
  {
    id: 'features-card-3-title',
    type: 'text',
    x: 140, y: 626, width: 264, height: 36,
    text: 'AI 자동화',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 3 Title',
  },
  {
    id: 'features-card-3-desc',
    type: 'text',
    x: 56, y: 700, width: 300, height: 100,
    text: 'GPT-4 기반 AI가 반복 업무를 완전 자동화합니다. 학습할수록 더 똑똑해지는 지능형 시스템입니다.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 3 Desc',
  },
  {
    id: 'features-card-3-tag',
    type: 'rect',
    x: 56, y: 850, width: 80, height: 24,
    fill: '{accent}',
    cornerRadius: 12,
    opacity: 0.15,
    locked: true,
    name: 'Card 3 Tag BG',
  },
  {
    id: 'features-card-3-tag-text',
    type: 'text',
    x: 56, y: 855, width: 80, height: 16,
    text: 'GPT-4 탑재',
    fontSize: 10,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Card 3 Tag',
  },

  // Card 4 (bottom-right)
  {
    id: 'features-card-4',
    type: 'rect',
    x: 440, y: 600, width: 380, height: 300,
    fill: '#ffffff',
    cornerRadius: 18,
    shadow: true,
    opacity: 0.97,
    locked: true,
    name: 'Card 4',
  },
  {
    id: 'features-card-4-icon-bg',
    type: 'circle',
    x: 456, y: 626, width: 64, height: 64,
    fill: '{primary}',
    opacity: 0.12,
    locked: true,
    name: 'Card 4 Icon BG',
  },
  {
    id: 'features-card-4-icon',
    type: 'text',
    x: 456, y: 638, width: 64, height: 40,
    text: '📊',
    fontSize: 28,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    draggable: true,
    editable: true,
    name: 'Card 4 Icon',
  },
  {
    id: 'features-card-4-title',
    type: 'text',
    x: 540, y: 626, width: 264, height: 36,
    text: '실시간 분석',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Card 4 Title',
  },
  {
    id: 'features-card-4-desc',
    type: 'text',
    x: 456, y: 700, width: 300, height: 100,
    text: '350개 이상의 지표를 실시간으로 모니터링합니다. 직관적인 대시보드로 인사이트를 즉시 확인하세요.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.55)',
    draggable: true,
    editable: true,
    name: 'Card 4 Desc',
  },
  {
    id: 'features-card-4-tag',
    type: 'rect',
    x: 456, y: 850, width: 100, height: 24,
    fill: '{primary}',
    cornerRadius: 12,
    opacity: 0.12,
    locked: true,
    name: 'Card 4 Tag BG',
  },
  {
    id: 'features-card-4-tag-text',
    type: 'text',
    x: 456, y: 855, width: 100, height: 16,
    text: '350+ 지표',
    fontSize: 10,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{primary}',
    draggable: true,
    editable: true,
    name: 'Card 4 Tag',
  },

  // Bottom accent line
  {
    id: 'features-bottom-line',
    type: 'rect',
    x: 0, y: 960, width: 860, height: 4,
    gradient: { from: '{accent}', to: '{primary}', direction: '90deg' },
    locked: true,
    name: 'Bottom Accent Line',
  },
  // Bottom label
  {
    id: 'features-bottom-label',
    type: 'text',
    x: 0, y: 980, width: 860, height: 30,
    text: '전체 기능 목록 보기 →',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.4)',
    draggable: true,
    editable: true,
    name: 'Bottom Label',
  },
  // Bottom deco dots
  {
    id: 'features-deco-dot-1',
    type: 'circle',
    x: 380, y: 1050, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.5,
    locked: true,
    name: 'Deco Dot 1',
  },
  {
    id: 'features-deco-dot-2',
    type: 'circle',
    x: 396, y: 1050, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.25,
    locked: true,
    name: 'Deco Dot 2',
  },
  {
    id: 'features-deco-dot-3',
    type: 'circle',
    x: 412, y: 1050, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.12,
    locked: true,
    name: 'Deco Dot 3',
  },
  {
    id: 'features-deco-dot-4',
    type: 'circle',
    x: 428, y: 1050, width: 8, height: 8,
    fill: '{accent}',
    opacity: 0.06,
    locked: true,
    name: 'Deco Dot 4',
  },
];

// 5. SPECS — 860 × 800
const specsTemplate = (): CompositionElement[] => [
  // Background
  {
    id: 'specs-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 800,
    fill: '#f8f8f8',
    locked: true,
    name: 'Background',
  },
  // Left accent stripe
  {
    id: 'specs-left-stripe',
    type: 'rect',
    x: 0, y: 0, width: 6, height: 800,
    fill: '{accent}',
    locked: true,
    name: 'Left Stripe',
  },
  // Section label
  {
    id: 'specs-label',
    type: 'text',
    x: 0, y: 50, width: 860, height: 24,
    text: '제품 사양',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Label',
  },
  // Title
  {
    id: 'specs-title',
    type: 'text',
    x: 60, y: 82, width: 740, height: 70,
    text: '상세 스펙 & 구성',
    fontSize: 40,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Title accent
  {
    id: 'specs-title-accent',
    type: 'rect',
    x: 340, y: 162, width: 180, height: 4,
    fill: '{accent}',
    cornerRadius: 2,
    locked: true,
    name: 'Title Accent',
  },

  // Row 1 (light)
  {
    id: 'specs-row-1-bg',
    type: 'rect',
    x: 40, y: 190, width: 780, height: 70,
    fill: '#ffffff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 1 BG',
  },
  {
    id: 'specs-row-1-label',
    type: 'text',
    x: 68, y: 214, width: 300, height: 24,
    text: '소재',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 1 Label',
  },
  {
    id: 'specs-row-1-value',
    type: 'text',
    x: 400, y: 214, width: 380, height: 24,
    text: '항공우주용 알루미늄 합금 7075-T6',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Row 1 Value',
  },

  // Row 2 (alternate)
  {
    id: 'specs-row-2-bg',
    type: 'rect',
    x: 40, y: 270, width: 780, height: 70,
    fill: '#f0f4ff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 2 BG',
  },
  {
    id: 'specs-row-2-label',
    type: 'text',
    x: 68, y: 294, width: 300, height: 24,
    text: '치수 (W × D × H)',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 2 Label',
  },
  {
    id: 'specs-row-2-value',
    type: 'text',
    x: 400, y: 294, width: 380, height: 24,
    text: '280 × 180 × 12 mm',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Row 2 Value',
  },

  // Row 3 (light)
  {
    id: 'specs-row-3-bg',
    type: 'rect',
    x: 40, y: 350, width: 780, height: 70,
    fill: '#ffffff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 3 BG',
  },
  {
    id: 'specs-row-3-label',
    type: 'text',
    x: 68, y: 374, width: 300, height: 24,
    text: '무게',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 3 Label',
  },
  {
    id: 'specs-row-3-value',
    type: 'text',
    x: 400, y: 374, width: 380, height: 24,
    text: '245g (배터리 포함)',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Row 3 Value',
  },

  // Row 4 (alternate)
  {
    id: 'specs-row-4-bg',
    type: 'rect',
    x: 40, y: 430, width: 780, height: 70,
    fill: '#f0f4ff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 4 BG',
  },
  {
    id: 'specs-row-4-label',
    type: 'text',
    x: 68, y: 454, width: 300, height: 24,
    text: '배터리 용량',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 4 Label',
  },
  {
    id: 'specs-row-4-value',
    type: 'text',
    x: 400, y: 454, width: 380, height: 24,
    text: '10,000 mAh (최대 72시간 연속 사용)',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Row 4 Value',
  },

  // Row 5 (light)
  {
    id: 'specs-row-5-bg',
    type: 'rect',
    x: 40, y: 510, width: 780, height: 70,
    fill: '#ffffff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 5 BG',
  },
  {
    id: 'specs-row-5-label',
    type: 'text',
    x: 68, y: 534, width: 300, height: 24,
    text: '방수 등급',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 5 Label',
  },
  {
    id: 'specs-row-5-value',
    type: 'text',
    x: 400, y: 534, width: 380, height: 24,
    text: 'IP68 (수심 2m, 30분 방수)',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Row 5 Value',
  },

  // Row 6 (alternate)
  {
    id: 'specs-row-6-bg',
    type: 'rect',
    x: 40, y: 590, width: 780, height: 70,
    fill: '#f0f4ff',
    cornerRadius: 8,
    locked: true,
    name: 'Row 6 BG',
  },
  {
    id: 'specs-row-6-label',
    type: 'text',
    x: 68, y: 614, width: 300, height: 24,
    text: '보증 기간',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Row 6 Label',
  },
  {
    id: 'specs-row-6-value',
    type: 'text',
    x: 400, y: 614, width: 380, height: 24,
    text: '3년 무상 A/S + 평생 소프트웨어 업데이트',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Row 6 Value',
  },

  // Bottom divider
  {
    id: 'specs-bottom-divider',
    type: 'rect',
    x: 40, y: 678, width: 780, height: 2,
    fill: '{accent}',
    opacity: 0.25,
    cornerRadius: 1,
    locked: true,
    name: 'Bottom Divider',
  },
  // Bottom note
  {
    id: 'specs-bottom-note',
    type: 'text',
    x: 40, y: 698, width: 780, height: 30,
    text: '* 사양은 사전 고지 없이 변경될 수 있습니다.',
    fontSize: 11,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(0,0,0,0.35)',
    draggable: true,
    editable: true,
    name: 'Bottom Note',
  },
  // Bottom deco large circle
  {
    id: 'specs-deco-circle',
    type: 'circle',
    x: 700, y: 660, width: 180, height: 180,
    fill: '{accent}',
    opacity: 0.05,
    locked: true,
    name: 'Deco Circle',
  },
];

// 6. REVIEWS — 860 × 1000
const reviewsTemplate = (): CompositionElement[] => [
  // Dark background
  {
    id: 'reviews-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 1000,
    fill: '{primary}',
    locked: true,
    name: 'Background',
  },
  // Overlay
  {
    id: 'reviews-overlay',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 1000,
    fill: 'rgba(0,0,0,0.3)',
    locked: true,
    name: 'Overlay',
  },
  // Deco circles
  {
    id: 'reviews-deco-tl',
    type: 'circle',
    x: -80, y: -80, width: 300, height: 300,
    fill: '{accent}',
    opacity: 0.07,
    locked: true,
    name: 'Deco TL',
  },
  {
    id: 'reviews-deco-br',
    type: 'circle',
    x: 680, y: 800, width: 260, height: 260,
    fill: '{accent}',
    opacity: 0.07,
    locked: true,
    name: 'Deco BR',
  },
  // Stars decoration — top center
  {
    id: 'reviews-stars-deco',
    type: 'text',
    x: 0, y: 52, width: 860, height: 28,
    text: '★ ★ ★ ★ ★',
    fontSize: 18,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#f59e0b',
    locked: true,
    name: 'Stars Deco',
  },
  // Title
  {
    id: 'reviews-title',
    type: 'text',
    x: 60, y: 92, width: 740, height: 80,
    text: '5만 명이 선택한 이유',
    fontSize: 44,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Title underline
  {
    id: 'reviews-title-ul',
    type: 'rect',
    x: 300, y: 182, width: 260, height: 4,
    fill: '#f59e0b',
    cornerRadius: 2,
    locked: true,
    name: 'Title Underline',
  },
  // Subtitle
  {
    id: 'reviews-subtitle',
    type: 'text',
    x: 140, y: 200, width: 580, height: 40,
    text: '실제 구매 고객들의 생생한 후기를 확인해 보세요.',
    fontSize: 14,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.55)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },

  // --- Review Card 1 ---
  {
    id: 'reviews-card-1',
    type: 'rect',
    x: 40, y: 270, width: 248, height: 320,
    fill: 'rgba(255,255,255,0.10)',
    cornerRadius: 16,
    stroke: 'rgba(255,255,255,0.15)',
    strokeWidth: 1,
    locked: true,
    name: 'Card 1',
  },
  {
    id: 'reviews-card-1-avatar',
    type: 'circle',
    x: 56, y: 288, width: 56, height: 56,
    fill: '{accent}',
    opacity: 0.7,
    locked: true,
    name: 'Avatar 1',
  },
  {
    id: 'reviews-card-1-avatar-initial',
    type: 'text',
    x: 56, y: 304, width: 56, height: 28,
    text: 'K',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    locked: true,
    name: 'Avatar 1 Initial',
  },
  {
    id: 'reviews-card-1-name',
    type: 'text',
    x: 122, y: 290, width: 148, height: 22,
    text: '김OO님',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Name 1',
  },
  {
    id: 'reviews-card-1-verified',
    type: 'text',
    x: 122, y: 310, width: 148, height: 18,
    text: '✓ 구매 인증',
    fontSize: 11,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Verified 1',
  },
  {
    id: 'reviews-card-1-stars',
    type: 'text',
    x: 56, y: 358, width: 216, height: 22,
    text: '★★★★★',
    fontSize: 16,
    fontFamily: 'Inter, sans-serif',
    color: '#f59e0b',
    locked: true,
    name: 'Stars 1',
  },
  {
    id: 'reviews-card-1-quote',
    type: 'text',
    x: 56, y: 390, width: 216, height: 160,
    text: '"처음엔 반신반의했는데 사용하고 바로 효과를 느꼈습니다. 지인들에게도 다 추천했어요. 이 가격에 이 품질이면 무조건 사야죠!"',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.7,
    color: 'rgba(255,255,255,0.80)',
    draggable: true,
    editable: true,
    name: 'Quote 1',
  },

  // --- Review Card 2 ---
  {
    id: 'reviews-card-2',
    type: 'rect',
    x: 306, y: 270, width: 248, height: 320,
    fill: 'rgba(255,255,255,0.10)',
    cornerRadius: 16,
    stroke: 'rgba(255,255,255,0.15)',
    strokeWidth: 1,
    locked: true,
    name: 'Card 2',
  },
  {
    id: 'reviews-card-2-avatar',
    type: 'circle',
    x: 322, y: 288, width: 56, height: 56,
    fill: '{primary}',
    opacity: 0.85,
    stroke: '{accent}',
    strokeWidth: 2,
    locked: true,
    name: 'Avatar 2',
  },
  {
    id: 'reviews-card-2-avatar-initial',
    type: 'text',
    x: 322, y: 304, width: 56, height: 28,
    text: 'L',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    locked: true,
    name: 'Avatar 2 Initial',
  },
  {
    id: 'reviews-card-2-name',
    type: 'text',
    x: 388, y: 290, width: 148, height: 22,
    text: '이OO님',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Name 2',
  },
  {
    id: 'reviews-card-2-verified',
    type: 'text',
    x: 388, y: 310, width: 148, height: 18,
    text: '✓ 구매 인증',
    fontSize: 11,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Verified 2',
  },
  {
    id: 'reviews-card-2-stars',
    type: 'text',
    x: 322, y: 358, width: 216, height: 22,
    text: '★★★★★',
    fontSize: 16,
    fontFamily: 'Inter, sans-serif',
    color: '#f59e0b',
    locked: true,
    name: 'Stars 2',
  },
  {
    id: 'reviews-card-2-quote',
    type: 'text',
    x: 322, y: 390, width: 216, height: 160,
    text: '"6개월째 매일 사용 중입니다. 초반에 비해 성능이 오히려 더 좋아진 느낌이에요. AS도 친절하고 빠르게 처리해 주셨습니다."',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.7,
    color: 'rgba(255,255,255,0.80)',
    draggable: true,
    editable: true,
    name: 'Quote 2',
  },

  // --- Review Card 3 ---
  {
    id: 'reviews-card-3',
    type: 'rect',
    x: 572, y: 270, width: 248, height: 320,
    fill: 'rgba(255,255,255,0.10)',
    cornerRadius: 16,
    stroke: 'rgba(255,255,255,0.15)',
    strokeWidth: 1,
    locked: true,
    name: 'Card 3',
  },
  {
    id: 'reviews-card-3-avatar',
    type: 'circle',
    x: 588, y: 288, width: 56, height: 56,
    fill: '#7c3aed',
    opacity: 0.75,
    locked: true,
    name: 'Avatar 3',
  },
  {
    id: 'reviews-card-3-avatar-initial',
    type: 'text',
    x: 588, y: 304, width: 56, height: 28,
    text: 'P',
    fontSize: 22,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    locked: true,
    name: 'Avatar 3 Initial',
  },
  {
    id: 'reviews-card-3-name',
    type: 'text',
    x: 654, y: 290, width: 148, height: 22,
    text: '박OO님',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Name 3',
  },
  {
    id: 'reviews-card-3-verified',
    type: 'text',
    x: 654, y: 310, width: 148, height: 18,
    text: '✓ 구매 인증',
    fontSize: 11,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Verified 3',
  },
  {
    id: 'reviews-card-3-stars',
    type: 'text',
    x: 588, y: 358, width: 216, height: 22,
    text: '★★★★★',
    fontSize: 16,
    fontFamily: 'Inter, sans-serif',
    color: '#f59e0b',
    locked: true,
    name: 'Stars 3',
  },
  {
    id: 'reviews-card-3-quote',
    type: 'text',
    x: 588, y: 390, width: 216, height: 160,
    text: '"디자인도 예쁘고 기능도 완벽합니다. 다른 브랜드 3개 써보다가 여기 정착했어요. 재구매 의향 200%입니다!"',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    lineHeight: 1.7,
    color: 'rgba(255,255,255,0.80)',
    draggable: true,
    editable: true,
    name: 'Quote 3',
  },

  // Bottom aggregate rating
  {
    id: 'reviews-aggregate-bg',
    type: 'rect',
    x: 40, y: 630, width: 780, height: 90,
    fill: 'rgba(255,255,255,0.07)',
    cornerRadius: 14,
    stroke: 'rgba(255,255,255,0.12)',
    strokeWidth: 1,
    locked: true,
    name: 'Aggregate BG',
  },
  {
    id: 'reviews-agg-score',
    type: 'text',
    x: 80, y: 652, width: 120, height: 50,
    text: '4.9',
    fontSize: 44,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#f59e0b',
    locked: true,
    name: 'Agg Score',
  },
  {
    id: 'reviews-agg-label',
    type: 'text',
    x: 210, y: 658, width: 200, height: 22,
    text: '평균 평점 (5점 만점)',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    color: 'rgba(255,255,255,0.60)',
    draggable: true,
    editable: true,
    name: 'Agg Label',
  },
  {
    id: 'reviews-agg-stars',
    type: 'text',
    x: 210, y: 682, width: 120, height: 22,
    text: '★★★★★',
    fontSize: 14,
    fontFamily: 'Inter, sans-serif',
    color: '#f59e0b',
    locked: true,
    name: 'Agg Stars',
  },
  {
    id: 'reviews-agg-count',
    type: 'text',
    x: 580, y: 658, width: 220, height: 22,
    text: '리뷰 4,872개',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Agg Count',
  },
  {
    id: 'reviews-agg-verified',
    type: 'text',
    x: 580, y: 682, width: 220, height: 22,
    text: '✓ 실구매자 검증',
    fontSize: 11,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    locked: true,
    name: 'Agg Verified',
  },

  // Bottom divider
  {
    id: 'reviews-bottom-divider',
    type: 'line',
    x: 80, y: 760, width: 700, height: 1,
    fill: 'rgba(255,255,255,0.08)',
    locked: true,
    name: 'Divider',
  },
  // Bottom text
  {
    id: 'reviews-bottom-text',
    type: 'text',
    x: 0, y: 780, width: 860, height: 30,
    text: '전체 후기 보기 →',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.35)',
    draggable: true,
    editable: true,
    name: 'Bottom Text',
  },
];

// 7. TRUST — 860 × 800
const trustTemplate = (): CompositionElement[] => [
  // Background
  {
    id: 'trust-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 800,
    fill: '#ffffff',
    locked: true,
    name: 'Background',
  },
  // Top accent band
  {
    id: 'trust-top-band',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 6,
    gradient: { from: '{primary}', to: '{accent}', direction: '90deg' },
    locked: true,
    name: 'Top Band',
  },
  // Section label
  {
    id: 'trust-label',
    type: 'text',
    x: 0, y: 50, width: 860, height: 24,
    text: '공식 인증 & 수상 내역',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Label',
  },
  // Title
  {
    id: 'trust-title',
    type: 'text',
    x: 60, y: 82, width: 740, height: 70,
    text: '검증된 신뢰, 공식 인정받은 품질',
    fontSize: 38,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.25,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Title underline
  {
    id: 'trust-title-ul',
    type: 'rect',
    x: 300, y: 162, width: 260, height: 4,
    fill: '{accent}',
    cornerRadius: 2,
    locked: true,
    name: 'Title Underline',
  },
  // Subtitle
  {
    id: 'trust-subtitle',
    type: 'text',
    x: 120, y: 180, width: 620, height: 44,
    text: '국제 기관으로부터 공식 인증 획득, 안전하고 신뢰할 수 있습니다.',
    fontSize: 14,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.65,
    color: 'rgba(0,0,0,0.45)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },

  // 5 certification circles (gold stroke) — y=270, spaced ~152px apart
  // Cert 1
  {
    id: 'trust-cert-1-outer',
    type: 'circle',
    x: 52, y: 270, width: 100, height: 100,
    fill: '#fffbeb',
    stroke: '#d97706',
    strokeWidth: 3,
    shadow: true,
    locked: true,
    name: 'Cert 1 Outer',
  },
  {
    id: 'trust-cert-1-inner',
    type: 'circle',
    x: 68, y: 286, width: 68, height: 68,
    fill: '#fef3c7',
    stroke: '#f59e0b',
    strokeWidth: 2,
    locked: true,
    name: 'Cert 1 Inner',
  },
  {
    id: 'trust-cert-1-icon',
    type: 'text',
    x: 52, y: 304, width: 100, height: 38,
    text: 'ISO\n9001',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#92400e',
    locked: true,
    name: 'Cert 1 Icon',
  },
  {
    id: 'trust-cert-1-label',
    type: 'text',
    x: 32, y: 386, width: 140, height: 36,
    text: '품질 경영\n국제 인증',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.4,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Cert 1 Label',
  },

  // Cert 2
  {
    id: 'trust-cert-2-outer',
    type: 'circle',
    x: 204, y: 270, width: 100, height: 100,
    fill: '#fffbeb',
    stroke: '#d97706',
    strokeWidth: 3,
    shadow: true,
    locked: true,
    name: 'Cert 2 Outer',
  },
  {
    id: 'trust-cert-2-inner',
    type: 'circle',
    x: 220, y: 286, width: 68, height: 68,
    fill: '#fef3c7',
    stroke: '#f59e0b',
    strokeWidth: 2,
    locked: true,
    name: 'Cert 2 Inner',
  },
  {
    id: 'trust-cert-2-icon',
    type: 'text',
    x: 204, y: 304, width: 100, height: 38,
    text: 'CE\n인증',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#92400e',
    locked: true,
    name: 'Cert 2 Icon',
  },
  {
    id: 'trust-cert-2-label',
    type: 'text',
    x: 184, y: 386, width: 140, height: 36,
    text: '유럽연합\n안전 인증',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.4,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Cert 2 Label',
  },

  // Cert 3
  {
    id: 'trust-cert-3-outer',
    type: 'circle',
    x: 380, y: 270, width: 100, height: 100,
    fill: '#fffbeb',
    stroke: '#d97706',
    strokeWidth: 3,
    shadow: true,
    locked: true,
    name: 'Cert 3 Outer',
  },
  {
    id: 'trust-cert-3-inner',
    type: 'circle',
    x: 396, y: 286, width: 68, height: 68,
    fill: '#fef3c7',
    stroke: '#f59e0b',
    strokeWidth: 2,
    locked: true,
    name: 'Cert 3 Inner',
  },
  {
    id: 'trust-cert-3-icon',
    type: 'text',
    x: 380, y: 304, width: 100, height: 38,
    text: 'KC\n인증',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#92400e',
    locked: true,
    name: 'Cert 3 Icon',
  },
  {
    id: 'trust-cert-3-label',
    type: 'text',
    x: 360, y: 386, width: 140, height: 36,
    text: '국가 통합\n안전 인증',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.4,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Cert 3 Label',
  },

  // Cert 4
  {
    id: 'trust-cert-4-outer',
    type: 'circle',
    x: 556, y: 270, width: 100, height: 100,
    fill: '#fffbeb',
    stroke: '#d97706',
    strokeWidth: 3,
    shadow: true,
    locked: true,
    name: 'Cert 4 Outer',
  },
  {
    id: 'trust-cert-4-inner',
    type: 'circle',
    x: 572, y: 286, width: 68, height: 68,
    fill: '#fef3c7',
    stroke: '#f59e0b',
    strokeWidth: 2,
    locked: true,
    name: 'Cert 4 Inner',
  },
  {
    id: 'trust-cert-4-icon',
    type: 'text',
    x: 556, y: 304, width: 100, height: 38,
    text: 'GMP\n인증',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#92400e',
    locked: true,
    name: 'Cert 4 Icon',
  },
  {
    id: 'trust-cert-4-label',
    type: 'text',
    x: 536, y: 386, width: 140, height: 36,
    text: '우수 제조\n시설 인증',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.4,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Cert 4 Label',
  },

  // Cert 5
  {
    id: 'trust-cert-5-outer',
    type: 'circle',
    x: 708, y: 270, width: 100, height: 100,
    fill: '#fffbeb',
    stroke: '#d97706',
    strokeWidth: 3,
    shadow: true,
    locked: true,
    name: 'Cert 5 Outer',
  },
  {
    id: 'trust-cert-5-inner',
    type: 'circle',
    x: 724, y: 286, width: 68, height: 68,
    fill: '#fef3c7',
    stroke: '#f59e0b',
    strokeWidth: 2,
    locked: true,
    name: 'Cert 5 Inner',
  },
  {
    id: 'trust-cert-5-icon',
    type: 'text',
    x: 708, y: 304, width: 100, height: 38,
    text: '수상\n2024',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.2,
    color: '#92400e',
    locked: true,
    name: 'Cert 5 Icon',
  },
  {
    id: 'trust-cert-5-label',
    type: 'text',
    x: 688, y: 386, width: 140, height: 36,
    text: '올해의 제품\n대상 수상',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.4,
    color: '{text}',
    draggable: true,
    editable: true,
    name: 'Cert 5 Label',
  },

  // Trust logos divider line
  {
    id: 'trust-divider',
    type: 'line',
    x: 60, y: 460, width: 740, height: 2,
    fill: 'rgba(0,0,0,0.06)',
    locked: true,
    name: 'Divider',
  },
  // Trust press quote
  {
    id: 'trust-press-quote',
    type: 'text',
    x: 80, y: 490, width: 700, height: 60,
    text: '"국내외 전문 기관이 인정한 최고 수준의 품질과 안전성.\n이제 안심하고 사용하세요."',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'Georgia, serif',
    textAlign: 'center',
    lineHeight: 1.7,
    color: 'rgba(0,0,0,0.5)',
    draggable: true,
    editable: true,
    name: 'Press Quote',
  },
  // Deco bottom left
  {
    id: 'trust-deco-bl',
    type: 'circle',
    x: -40, y: 640, width: 200, height: 200,
    fill: '{accent}',
    opacity: 0.05,
    locked: true,
    name: 'Deco BL',
  },
  // Deco bottom right
  {
    id: 'trust-deco-br',
    type: 'circle',
    x: 700, y: 640, width: 200, height: 200,
    fill: '{primary}',
    opacity: 0.05,
    locked: true,
    name: 'Deco BR',
  },
];

// 8. CTA — 860 × 800
const ctaTemplate = (): CompositionElement[] => [
  // Gradient background
  {
    id: 'cta-bg',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 800,
    gradient: { from: '{primary}', to: '#0f0c29', direction: '145deg' },
    locked: true,
    name: 'Background',
  },
  // Overlay
  {
    id: 'cta-overlay',
    type: 'rect',
    x: 0, y: 0, width: 860, height: 800,
    fill: 'rgba(0,0,0,0.2)',
    locked: true,
    name: 'Overlay',
  },
  // Large deco circle — top right
  {
    id: 'cta-deco-tr',
    type: 'circle',
    x: 640, y: -120, width: 400, height: 400,
    fill: '{accent}',
    opacity: 0.10,
    locked: true,
    name: 'Deco TR',
  },
  // Medium deco circle — bottom left
  {
    id: 'cta-deco-bl',
    type: 'circle',
    x: -100, y: 560, width: 320, height: 320,
    fill: '{accent}',
    opacity: 0.08,
    locked: true,
    name: 'Deco BL',
  },
  // Small accent circle — mid
  {
    id: 'cta-deco-mid',
    type: 'circle',
    x: 780, y: 380, width: 80, height: 80,
    fill: '#ffffff',
    opacity: 0.05,
    locked: true,
    name: 'Deco Mid',
  },
  // Small accent circle — mid left
  {
    id: 'cta-deco-ml',
    type: 'circle',
    x: 20, y: 200, width: 60, height: 60,
    fill: '{accent}',
    opacity: 0.15,
    locked: true,
    name: 'Deco ML',
  },
  // Decorative horizontal lines
  {
    id: 'cta-deco-line-1',
    type: 'line',
    x: 0, y: 180, width: 200, height: 2,
    fill: '{accent}',
    opacity: 0.2,
    locked: true,
    name: 'Deco Line 1',
  },
  {
    id: 'cta-deco-line-2',
    type: 'line',
    x: 660, y: 620, width: 200, height: 2,
    fill: '{accent}',
    opacity: 0.2,
    locked: true,
    name: 'Deco Line 2',
  },

  // Urgency badge
  {
    id: 'cta-urgency-bg',
    type: 'rect',
    x: 310, y: 100, width: 240, height: 38,
    fill: '{accent}',
    cornerRadius: 19,
    opacity: 0.9,
    locked: true,
    name: 'Urgency BG',
  },
  {
    id: 'cta-urgency-text',
    type: 'text',
    x: 310, y: 110, width: 240, height: 22,
    text: '🔥 한정 특가 — 오늘까지',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Urgency Text',
  },

  // Main title
  {
    id: 'cta-title',
    type: 'text',
    x: 60, y: 162, width: 740, height: 120,
    text: '지금 시작하면\n달라집니다',
    fontSize: 60,
    fontWeight: 900,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.15,
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Title',
  },
  // Accent line below title
  {
    id: 'cta-accent-line',
    type: 'rect',
    x: 280, y: 294, width: 300, height: 6,
    gradient: { from: '{accent}', to: 'rgba(255,255,255,0)', direction: '90deg' },
    cornerRadius: 3,
    locked: true,
    name: 'Accent Line',
  },

  // Subtitle
  {
    id: 'cta-subtitle',
    type: 'text',
    x: 100, y: 316, width: 660, height: 80,
    text: '지금 구매하면 특별 할인가와 보너스 구성품을 함께 받으실 수 있습니다. 이 기회를 놓치지 마세요.',
    fontSize: 17,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    lineHeight: 1.7,
    color: 'rgba(255,255,255,0.72)',
    draggable: true,
    editable: true,
    name: 'Subtitle',
  },

  // Price block
  {
    id: 'cta-price-old',
    type: 'text',
    x: 0, y: 410, width: 860, height: 30,
    text: '정상가 198,000원',
    fontSize: 14,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.4)',
    locked: true,
    name: 'Price Old',
  },
  {
    id: 'cta-price-new',
    type: 'text',
    x: 0, y: 440, width: 860, height: 56,
    text: '79,000원',
    fontSize: 48,
    fontWeight: 900,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '{accent}',
    draggable: true,
    editable: true,
    name: 'Price New',
  },
  {
    id: 'cta-price-badge',
    type: 'rect',
    x: 480, y: 448, width: 80, height: 28,
    fill: '#ef4444',
    cornerRadius: 14,
    locked: true,
    name: 'Discount Badge BG',
  },
  {
    id: 'cta-price-badge-text',
    type: 'text',
    x: 480, y: 455, width: 80, height: 18,
    text: '60% OFF',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    locked: true,
    name: 'Discount Badge Text',
  },

  // CTA button — large rect
  {
    id: 'cta-btn',
    type: 'rect',
    x: 220, y: 518, width: 420, height: 72,
    fill: '{accent}',
    cornerRadius: 36,
    shadow: true,
    draggable: true,
    name: 'CTA Button',
  },
  {
    id: 'cta-btn-text',
    type: 'text',
    x: 220, y: 540, width: 420, height: 28,
    text: '지금 바로 구매하기 →',
    fontSize: 22,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: '#ffffff',
    draggable: true,
    editable: true,
    name: 'Button Text',
  },
  // Sub-button label
  {
    id: 'cta-sub-btn-text',
    type: 'text',
    x: 220, y: 606, width: 420, height: 20,
    text: '30일 무료 체험 · 카드 불필요',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.5)',
    locked: true,
    name: 'Sub Button Text',
  },

  // Trust row
  {
    id: 'cta-trust-1',
    type: 'text',
    x: 80, y: 650, width: 220, height: 24,
    text: '🔒  256-bit 보안 결제',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.5)',
    locked: true,
    name: 'Trust 1',
  },
  {
    id: 'cta-trust-2',
    type: 'text',
    x: 320, y: 650, width: 220, height: 24,
    text: '🚚  당일 무료 배송',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.5)',
    locked: true,
    name: 'Trust 2',
  },
  {
    id: 'cta-trust-3',
    type: 'text',
    x: 560, y: 650, width: 220, height: 24,
    text: '↩️  30일 무조건 환불',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.5)',
    locked: true,
    name: 'Trust 3',
  },

  // Bottom gradient fade
  {
    id: 'cta-bottom-fade',
    type: 'rect',
    x: 0, y: 720, width: 860, height: 80,
    gradient: { from: 'rgba(0,0,0,0)', to: 'rgba(0,0,0,0.4)', direction: '180deg' },
    locked: true,
    name: 'Bottom Fade',
  },
];

// ---------------------------------------------------------------------------
// Template registry
// ---------------------------------------------------------------------------
type TemplateFactory = () => CompositionElement[];

const TEMPLATE_REGISTRY: Record<
  string,
  { factory: TemplateFactory; width: number; height: number; background: string }
> = {
  hero: {
    factory: heroTemplate,
    width: 860,
    height: 900,
    background: '{primary}',
  },
  problem: {
    factory: problemTemplate,
    width: 860,
    height: 1000,
    background: '#f5f5f7',
  },
  solution: {
    factory: solutionTemplate,
    width: 860,
    height: 900,
    background: '#ffffff',
  },
  features: {
    factory: featuresTemplate,
    width: 860,
    height: 1100,
    background: '{primary}',
  },
  specs: {
    factory: specsTemplate,
    width: 860,
    height: 800,
    background: '#f8f8f8',
  },
  reviews: {
    factory: reviewsTemplate,
    width: 860,
    height: 1000,
    background: '{primary}',
  },
  trust: {
    factory: trustTemplate,
    width: 860,
    height: 800,
    background: '#ffffff',
  },
  cta: {
    factory: ctaTemplate,
    width: 860,
    height: 800,
    background: '{primary}',
  },
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------
export function getCompositionTemplate(
  sectionType: string,
  colors: { primary: string; accent: string; text: string }
): SectionComposition {
  const entry = TEMPLATE_REGISTRY[sectionType];

  if (!entry) {
    // Fallback: blank canvas
    return {
      sectionType,
      variantId: `${sectionType}-default`,
      width: 860,
      height: 900,
      background: colors.primary,
      elements: [
        {
          id: `${sectionType}-bg`,
          type: 'rect',
          x: 0, y: 0, width: 860, height: 900,
          fill: colors.primary,
          locked: true,
          name: 'Background',
        },
        {
          id: `${sectionType}-placeholder`,
          type: 'text',
          x: 60, y: 420, width: 740, height: 60,
          text: sectionType.toUpperCase(),
          fontSize: 32,
          fontWeight: 700,
          fontFamily: 'Inter, sans-serif',
          textAlign: 'center',
          color: '#ffffff',
          draggable: true,
          editable: true,
          name: 'Placeholder',
        },
      ],
    };
  }

  const rawElements = entry.factory();
  const processedElements = processElements(rawElements, colors);
  const background = replacePlaceholders(entry.background, colors);

  return {
    sectionType,
    variantId: `${sectionType}-default`,
    width: entry.width,
    height: entry.height,
    background,
    elements: processedElements,
  };
}

export const SUPPORTED_SECTION_TYPES = Object.keys(TEMPLATE_REGISTRY);
